### ISSUE TITLE
Snapdrop

### ISSUE THREAD

**Issue by virtualb1** [bromite/bromite#2007]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

100.0.4896.135

### Device architecture

arm64-v8a

### Android version

12

### Device model

SM-A405FN

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No.

### Describe the bug

Files can't be sent.

### Steps to reproduce the bug

Go to https://snapdrop.net/
and try to send a file to your other device.

### Expected behavior

Sending end receiving files succesfully.

**Comment by csagan5** [comment]
Duplicate of #1693

**Comment by virtualb1** [comment]
The reason why I started the discussion before submitting the bug was that I expected this behaviour. I am sorry that I can't tell you what is causing the problem, but if you already know why the app/site does not work on my devices with bromite you could have just told me, instead of trying to insult me without making it obvious, in the discussion. 
In case you don't know what is causing the problem please reopen the issue. If you don't want to reopen it I will submit a new one till it is fixed or I get properly informed why It can't be fixed.

**Comment by virtualb1** [comment]
I should have paid more attention but at least finally I realized my problem is related to webRTC. Sadly snapdrop is using webRTC.

**Comment by csagan5** [comment]
1. you have opened an issue without following the template
2. then you started a discussion
3. then you opened a new issue when I told you that discussions are not for bug reports
4. I closed the new issue as a duplicate because you have still not searched for existing ones before opening the issue (as written in the issue template itself)
5. you complain and say that I am insulting you, and still have not checked the issue even after I linked it as duplicate

If you cannot spare the time to read anything then I cannot spare the time to read or write anything, sorry.

> Sadly snapdrop is using webRTC.

#1965 might help with any website that needs webRTC; however not even the Snapdrop author or any user has ever figured out what is exactly needed in terms of APIs. It is probably webRTC, but it is disabled for privacy reasons (see https://github.com/bromite/bromite/wiki/WebRTC) and in general Bromite will always favour privacy over features when such features break privacy.

**Comment by virtualb1** [comment]
1. As I know this is the first time I opened an issue, if you received any other, I am sorry, it should be accidental. 
2. I admit my laziness I opened the discussion because I already knew some people were working on issues before, which affected snapdrop. I was hoping someone could give me a quick answer.  Because in the previously closed issue the reason for why still not working, after work being done was not obvious(at least if you are not paying attention to details)(and you even told fm-sys to feel free to open a new issue after figuring out what the problem is). 
I just wanted to make sure I understand the situation well, so I opened a discussion to ask two questions. Where else can people ask questions, if not in the discussion?
 I opened a general discussion, I thought there people can chat about anything associated with bromite. Please tell me if I am wrong and I will not open a discussion ever again if not absolutely necessary. 
3. I opened the issue because I did not get a straight answer for my questions, and you closed the discussion.

Please do not misinterpret the things I wrote, I have no bad intentions, I just can't express it in a better way, probably because I don't speak the language well enough.

I am thankful for your work associated with bromite. I am sorry that this discussion wasted your time. After I realized the problem is related to webRTC I figured out the rest, but thank you for finally properly informing me.
