### ISSUE TITLE
Video playback tests for v86

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#755]
### Bromite version

Version: `86.0.4240.55`
Arch: `arm64`
Android version: any
Device model: any

I have opened this issue to perform some tests related to video playback (see #445); the AImageReader issues might be fixed by upstream now in v86 (no news since February 20th there: https://bugs.chromium.org/p/chromium/issues/detail?id=977583).

# Versions to test

1. [Bromite v86 - no AImageReader patches](https://fdroid.bromite.org/fdroid/bromite/v86_arm64_ChromePublic.apk) this should be the next released version
2. [Bromite v86 with AImageReader patches](https://fdroid.bromite.org/fdroid/bromite/v86_arm64_ChromePublic_AImageReader_patched.apk)

# Current issue

No sound on Chromium/Bromite v86 for some device types, use https://www.provideocoalition.com/aac-test-does-this-your-device-play-this-file/ for a test.

**Comment by csagan5** [comment]
@aluo-x @kyelbek @l-easwar-akiyama @tiagossa1 @kkkrist @proteriax if you have the chance could you test these 2 versions linked above and report back the Android version and whether they crash or not with video playback?

Thanks

**Comment by kyelbek** [comment]
Patched one (second link) is broken for me. Revolut(?) logo in place of Google's when search provider is set to Google. Can't load any site. Reinstalling doesn't help. No private DNS is set. Trying to connect to any site using IP resolves site domain and replacing IP in address bar.
First link is giving me 404.
Still same OS, Lineage 17.1 (10), Lenovo P2.
![Screenshot_20200928-212335_Bromite](https://user-images.githubusercontent.com/9123992/94478393-8241a700-01d3-11eb-9155-057e67ad854a.png)
![Screenshot_20200928-212543_Bromite](https://user-images.githubusercontent.com/9123992/94478415-88378800-01d3-11eb-890f-2a0854d1f1bf.png)

**Comment by csagan5** [comment]
> First link is giving me 404.

Can you please retry? The second one was uploading, bu the first one has been there since the beginning. They should be both working fine.

> No private DNS is set.

Privacy -> Secure DNS is off? It sure looks like it is still enabled. Have you tried restarting the browser?

**Comment by kyelbek** [comment]
Added an edit already, got both versions.

> Privacy -> Secure DNS is off? It sure looks like it is still enabled. Have you tried restarting the browser?
Yeah, it was the case.

Both are working fine for me. Tried few times switching between and checking link from previous thread and one which was failing previously on YouTube too. Can't reproduce. Will report if it fail at some point.

**Comment by csagan5** [comment]
@kyelbek thanks for your tests; (1) is the version we want to use for next release.

**Comment by csagan5** [comment]
Fixed in `86.0.4240.66`.

**Comment by aluo-x** [comment]
This release broke aac audio playback for me.
This link plays on bromite v85 but not on v86.0.4240.70:
https://www.provideocoalition.com/aac-test-does-this-your-device-play-this-file/

I'm inclined to believe this is not bromite specific, as using the provided chromium builds also results in no audio. But rolling back to v85 does give me audio.

**Comment by ouzowtf** [comment]
Test with latest 86.0.4240.73

**Comment by aluo-x** [comment]
Still broken on arm64 for 86.0.4240.73

**Comment by jaydm99** [comment]
Audio still broken on some sites. I tested both on Bromite and Chromium version 86.0.4240.70

**Comment by csagan5** [comment]
This file is also reported to not be working: https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/Chimera-AV1-8bit-480x270-552kbps.mp4

Has anyone found an upstream issue for this? Does anyone have `arm` (not 64-bit)?

**Comment by aluo-x** [comment]
Just tried with the armv7 chromium 86.0.4240.73 that you provide, also no audio. So I guess this is probably upstream.

**Comment by aluo-x** [comment]
Also @csagan5 I don't believe the woolyss link you give has sound in the original stream. It also has no sound on v85, but the link I gave works on v85 but not v86.

**Comment by csagan5** [comment]
@aluo-x thanks for testing.

Please test with the AAudio flag disabled, it was [recently turned on by default](https://github.com/chromium/chromium/commit/a3e93aa57fcd7fab412c040a4bf996500383658a).

Has anyone located the upstream Chromium issue for this? I could not identify it so far. If none can be found, you might want to open one.

**Comment by aluo-x** [comment]
I tried https://www.provideocoalition.com/aac-test-does-this-your-device-play-this-file/
with aaudio toggled on/off & restarting bromite, it had no effect. No audio was played from the link.

A few notes from looking at media internals:
No significant differences in Players tab, or Audio tab.
In audio focus (for this link only), on chrome 85 there is an active session, but no active session in 86.
In audio focus (for youtube), there are active sessions in chrome 85 & 86

**Comment by csagan5** [comment]
> So I guess this is probably upstream.

It is an upstream bug, but upstream builds the browser with a different combination of GN flags, so if it does not affect one of the combinations they use there are little chances that it will be discovered and fixed.

Possibly related issues:
* https://bugs.chromium.org/p/chromium/issues/detail?id=1119947
* https://bugs.chromium.org/p/chromium/issues/detail?id=1094571
* https://bugs.chromium.org/p/chromium/issues/detail?id=758668

> A few notes from looking at media internals:
> No significant differences in Players tab, or Audio tab.

Is there anything in the Javascript console or logcat output which can give us some leads?

**Comment by kkkrist** [comment]
> Is there anything in the Javascript console or logcat output which can give us some leads?

Not in the devtools console. Here's a video showing that the audio file is actually fetched and processed even though I can't hear any output:

https://kh9.mundpropaganda.net/bromite-no-audio.mp4

Everything looks normal. I get a player notification with a working play/pause button etc. I'm using a OnePlus Nord (AC2003) with Android 10 (patch level 09/01/20, Build AC2003_14_200926)

I've also pulled a logcat. It's huge and there's a lot of private data in there, so I'd rather email it to you if you're interested.

<details>
<summary>Logcat bits</summary>

```
10-08 15:56:13.405   787 12302 E volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
10-08 15:56:13.407   787 14958 E msm8974_platform: platform_check_backends_match: Invalid snd_device =
10-08 15:56:13.407   787 14958 E voice   : voice_is_in_call_rec_stream: input stream is NULL
10-08 15:56:13.407   787 14958 E audio_hw_utils: send_app_type_cfg_for_device: Could not get ctl for mixer cmd
 - Audio Stream Capture 40 App Type Cfg
10-08 15:56:13.410   787 14958 E audio_hw_tfa98xx_feedback: audio_extn_tfa98xx_start_feedback: pcm device tx i
d=40
10-08 15:56:13.423   787 14958 E soundtrigger: audio_extn_sound_trigger_update_stream_status: invalid input de
vice 0x0, for event 3
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found
(result=-100) for topology 0x10012d00 and apptype 0x11134
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with stat
us -100
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found
(result=-100) for topology 0x10012d00 and apptype 0x11134
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with stat
us -100
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found
(result=-100) for topology 0x10012d00 and apptype 0x11134
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with stat
us -100
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found
(result=-100) for topology 0x10012d00 and apptype 0x11134
(result=-100) for topology 0x10012d00 and apptype 0x11134                                             [74/917]
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with stat
us -100
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found
(result=-100) for topology 0x10012d00 and apptype 0x11134
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with stat
us -100
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found
(result=-100) for topology 0x10012d00 and apptype 0x11134
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with stat
us -100
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found
(result=-100) for topology 0x10012d00 and apptype 0x11134
10-08 15:56:13.621   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with stat
us -100
10-08 15:56:13.622   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] active device/stream not found
(result=-100) for topology 0x10012d00 and apptype 0x11134
10-08 15:56:13.622   787   876 E ACDB-LOADER: [acdb_loader_adsp_set_audio_cal] set parameters failed with stat
us -100
10-08 15:56:13.622  2898  5018 E se.dirac.gef: sendGefParameter returned: 0
10-08 15:56:13.624  2413  2413 E Icon    : Unable to load resource 0x7f080000 from pkg=org.bromite.bromite
10-08 15:56:13.624  2413  2413 E Icon    : android.content.res.Resources$NotFoundException: Drawable org.bromi
te.bromite:drawable/0_resource_name_obfuscated with resource ID #0x7f080000
10-08 15:56:13.624  2413  2413 E Icon    : Caused by: android.content.res.Resources$NotFoundException: File re
s/5S.xml from drawable resource ID #0x7f080000
```
</details>

**Comment by aluo-x** [comment]
I cannot reproduce this bug on the official armv7 86.0.4240.75 chrome for Android. Sound works fine on the official builds. Tested with multiple links that don't work with the bromite v86 build.

If the bug is upstream, the official builds aren't triggering this.

**Comment by kkkrist** [comment]
Btw, 32-bit vs. 64-bit does not make a difference for me (tried the side-by-side Chromium builds from the F-Droid repo), both have no sound.

Current official Chrome from Play Store (86.0.4240.75, 32-bit) works fine.

**Comment by uazo** [comment]
> "Reason for revert: Breaks played out audio too"
> Add callback to WebMediaPlayerImpl to notify when a redirect occurs

I think that's why.
Here my log:

```
10-09 19:08:32.536 22198 22266 V chromium: [VERBOSE1:url_loader.cc(1039)] Connection obtained for URL request to
 https://www.podtrac.com/pts/redirect.mp3/beyondpodcasting.com/wp-content/uploads/2018/10/BeyondPodasting-bonus-AAC.m4a?_=3: 
TransportInfo{ type = TransportType::kDirect, endpoint = 44.239.236.27:443 }
```

and it's really a redirect.

```
cache-control: no-cache, no-store, must-revalidate
content-length: 233
content-type: text/html; charset=utf-8
date: Fri, 09 Oct 2020 17:17:37 GMT
expires: -1
location: https://beyondpodcasting.com/wp-content/uploads/2018/10/BeyondPodasting-bonus-AAC.m4a?_=3
pragma: no-cache
server: Microsoft-IIS/10.0
status: 302
x-aspnet-version: 4.0.30319
x-aspnetmvc-version: 4.0
x-machine: EAST3
x-powered-by: ASP.NET
```

@csagan5 
i tried to compile with carriage return before spaces in https://github.com/bromite/bromite/blob/master/build/GN_ARGS#L15 
it's intentional?
I've seen after that

```
10-09 19:08:32.978 22270 22320 V chromium: [VERBOSE1:media_codec_util.cc(379)] IsKnownUnacceleratedDefault codec for vp8 : OMX.google.vp8.encoder, direction: 1
```

after doing that i saw that the proprietary codecs are activated, before they weren't.

**Comment by uazo** [comment]
I compiled and tried Bromite patchs with 86.0.4240.75, it seems to work

**Comment by csagan5** [comment]
> If the bug is upstream, the official builds aren't triggering this.
> Current official Chrome from Play Store (86.0.4240.75, 32-bit) works fine.

It is already 2 versions forward.

> ICYMI: [86.0.4240.75...86.0.4240.73](https://github.com/chromium/chromium/compare/86.0.4240.73...86.0.4240.75) over in the official Chromium repo contains a [reverted commit](https://github.com/chromium/chromium/commit/bc58153181d6566a111816133b750dc276afc632), citing "Reason for revert: Breaks played out audio too". Can this be related to the problem described in the latest comments here?

Most likely yes; the reported issue is private, probably because it is reported from a partner or it has security implications.

I will release a new build.

> i tried to compile with carriage return before spaces in https://github.com/bromite/bromite/blob/master/build/GN_ARGS#L15
> it's intentional?

It does not affect the build, they will be parsed anyways by GN whether separated by space or newlines.

**Comment by uazo** [comment]
> It does not affect the build, they will be parsed anyways by GN whether separated by space or newlines.

really, it doesn't seem like that, I can try again, but that's what I did

try it yourself, you need a debug version, then activate trace 1
```
echo "--enable-logging --v=1" > /data/local/tmp/chrome-command-line 
```
you will see
```
10-09 13:53:00.065  7407  7605 V chromium: [VERBOSE1:batching_media_log.cc(40)] MediaEvent: {"debug":"Warning, FFmpegDemuxer failed to create a valid/supported video decoder configuration from muxed stream, config:codec: unknown, profile: unknown, level: not available, alpha_mode: is_opaque, coded size: [0,0], visible rect: [0,0,0,0], natural size: [0,0], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:SMPTE170M, transfer:SMPTE170M, matrix:SMPTE170M, range:LIMITED}"}
10-09 13:53:00.066  7407  7605 V chromium: [VERBOSE1:batching_media_log.cc(40)] MediaEvent: {"info":"FFmpegDemuxer: skipping invalid or unsupported video track"}
```
with newlines
```
10-09 19:08:32.978 22270 22320 V chromium: [VERBOSE1:media_codec_util.cc(379)] IsKnownUnacceleratedDefault codec for vp8 : OMX.google.vp8.encoder, direction: 1
```

here https://source.chromium.org/chromium/chromium/src/+/master:media/ffmpeg/ffmpeg_common.cc;l=482 related code

**Comment by uazo** [comment]
sorry, it looks like you're right.
I've tried without newline and adding `static_assert(false, "Compiled!");` after `#if BUILDFLAG(USE_PROPRIETARY_CODECS)` and it not builds.
I'll try to understand why I have a different message...

**Comment by csagan5** [comment]
You can check the [GN reference](https://gn.googlesource.com/gn/+/master/docs/reference.md).

> I'll try to understand why I have a different message...

I could be due to the in-browser flags related to acceleration, however I do not think it is related to the issue we are discussing here.

**Comment by csagan5** [comment]
The remaining audio issue should be fixed in `86.0.4240.92`.
