### ISSUE TITLE
User agent customization patch

### ISSUE THREAD

**Issue by csagan5** [bromite/bromite#819]
The patch for user agent customization in `87.0.4280.68` does not work; original version does not allow SystemWebView to be built.

See also: #798 #807

**Comment by uazo** [comment]
so to understand, the current version released and available for installation works because you used my version. the one available in master modified by you to also compile systemwebview does not work and needs to be fixed, correct?

**Comment by csagan5** [comment]
> so to understand, the current version released and available for installation works because you used my version.

No, that would not be possible. It does not build SystemWebView.

> the one available in master modified by you to also compile systemwebview does not work and needs to be fixed, correct?

The patches in current master are those used to build the latest release, however the custom user agent feature does not work.

**Comment by uazo** [comment]
> The patches in current master are those used to build the latest release, however the custom user agent feature does not work.

then the bug is more serious, because the current build downloaded via f-droid works for me.
@csagan5 can you give me some more info?

**Comment by csagan5** [comment]
> then the bug is more serious, because the current build downloaded via f-droid works for me (tested on Android 9 and 10)

I doubt it works. Reproduce with these steps (from vanilla Bromite):
1. enter a custom user user agent for mobile
2. go to https://www.bromite.org/detect and click Start test
3. verify that UA has not changed

This is what should be fixed:
* if user changes the user agent string for mobile/desktop the user should not toggle desktop mode from the hamburger menu to see an effect
* the custom user agent strings should work regardless of the current value for "Sticky mode"
* when user enters a custom UA (for either desktop or mobile) the corresponding flag should be set (right now it does not, until you hit the radio box)

**Comment by uazo** [comment]
> verify that UA has not changed

ok, it seems that javascript does not detect the change.

> if user changes the user agent string for mobile/desktop the user should not toggle desktop mode from the hamburger menu to see an effect

currently it is only necessary to refresh the page, simply because the http request must be redone with the new ua. I had already thought about doing it automatically, but I didn't want to refresh each tab, having read that some users had more than 100 open.

> the custom user agent strings should work regardless of the current value for "Sticky mode"

that's it, is not it? could you double check?

> when user enters a custom UA (for either desktop or mobile) the corresponding flag should be set (right now it does not, until you hit the radio box)

this is a chromium bug, but i think it can be fixed.

**Comment by csagan5** [comment]
> > if user changes the user agent string for mobile/desktop the user should not toggle desktop mode from the hamburger menu to see an effect
> 
> currently it is only necessary to refresh the page, simply because the http request must be redone with the new ua. I had already thought about doing it automatically, but I didn't want to refresh each tab, having read that some users had more than 100 open.

It is not a refresh problem. If the desktop mode is not toggled ON, it does not work. When it is toggled, the UA is correctly changed.

> > verify that UA has not changed
> 
> ok, it seems that javascript does not detect the change.

Not at all, the `User-Agent` header is wrong and it is always the same as the Javascript one.



> > the custom user agent strings should work regardless of the current value for "Sticky mode"
> 
> that's it, is not it? could you double check?

Yes, this is fine. The problem is that the header is overriden only when desktop mode is ON.

**Comment by uazo** [comment]
> It is not a refresh problem. If the desktop mode is not toggled ON, it does not work. When it is toggled, the UA is correctly changed.

> Not at all, the User-Agent header is wrong and it is always the same as the Javascript one.

Ok, I think I understand. how much ram does your cell phone have?

**Comment by leacha69** [comment]
Here's my observation.

Change UA mobile & desktop. Using mobile, go to any UA site and custom UA is read. Enter chrome://restart, go to various UA sites and default UA for mobile is read. Settings still show custom UA is chosen.
Repeat procedure using desktop mode (sticky in menu) all is well. It seems mobile mode is the culprit.

Android 10, SM-T860, 8GB ram

**Comment by uazo** [comment]
> Enter chrome://restart, go to various UA sites and default UA for mobile is read

this is because of the modification made by carl. on reboot it does not reassign the UA.

in any case, it seems that webkit does not detect the change, just checked with the remote debuggers
![image](https://user-images.githubusercontent.com/29201891/99908390-b375b980-2ce2-11eb-8c31-5d1e7c6fe829.png)
![image](https://user-images.githubusercontent.com/29201891/99908398-b7a1d700-2ce2-11eb-9558-f459f6b55be5.png)

**Comment by uazo** [comment]
ok, i found, the issue is that the cache is not revalidated when the ua is changed. try to clean and refresh.

**Comment by csagan5** [comment]
> this is because of the modification made by carl. on reboot it does not reassign the UA.

You mean the modification to fix this build error?
```
ld.lld: error: undefined symbol: switches::kUserAgent
>>> referenced by string_piece.h:166 (../../base/strings/string_piece.h:166)
>>>               thinlto-cache/Thin-11b025.tmp.o:(content::BrowserStartupComplete(int))

ld.lld: error: undefined symbol: g_browser_process
>>> referenced by browser_startup_controller.cc:35 (../../content/browser/android/browser_startup_controller.cc:35)
>>>               thinlto-cache/Thin-11b025.tmp.o:(content::BrowserStartupComplete(int))

ld.lld: error: undefined symbol: prefs::kOverrideUserAgentEnabled
>>> referenced by browser_startup_controller.cc:37 (../../content/browser/android/browser_startup_controller.cc:37)
>>>               thinlto-cache/Thin-11b025.tmp.o:(content::BrowserStartupComplete(int))

ld.lld: error: undefined symbol: prefs::kOverrideUserAgent
>>> referenced by browser_startup_controller.cc:39 (../../content/browser/android/browser_startup_controller.cc:39)
>>>               thinlto-cache/Thin-11b025.tmp.o:(content::BrowserStartupComplete(int))

ld.lld: error: undefined symbol: prefs::kDesktopModeViewportMetaEnabled
>>> referenced by browser_startup_controller.cc:48 (../../content/browser/android/browser_startup_controller.cc:48)
>>>               thinlto-cache/Thin-11b025.tmp.o:(content::BrowserStartupComplete(int))
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If you can come up with a better patch I will be happy to merge the PR; unfortunately right now even if it builds there are some issues left.

**Comment by uazo** [comment]
>  You mean the modification to fix this build error?

yes, in BrowserStartupComplete I recovery the ua at startup. but maybe I can move it to the PrivacyPreferenceManager and call it at the java side start after the native init, so I take it out from there, even though I don't understand why you don't like it

> this is because of the modification made by carl

I have to apologize anyway, sometimes I'm too Italian... next time I ask you the courtesy to wait before releasing patchs not fully verified because I didn't expect to have to fix something in production not detected by users, I didn't think there was so much urgency

> the issue is that the cache is not revalidated 

Regarding the cache problem we have two solutions: either I delete it when the ua is changed, or I change everything and inject it to the RenderFrameHost trying to imitate the devtools, since the cache works there. Obviously the second is a bit more complex. what do you think about it?

**Comment by csagan5** [comment]
> next time I ask you the courtesy to wait before releasing patchs not fully verified

The PR was not marked as a draft, there was nothing to mark it as "not ready" or not tested.

> I didn't think there was so much urgency

There was no urgency before and there is no urgency now; it is not a critical bug. We already have an issue open; it will cause some user frustration but it is not a widely used feature either.

**Comment by csagan5** [comment]
> Regarding the cache problem we have two solutions: either I delete it when the ua is changed, or I change everything and inject it to the RenderFrameHost trying to imitate the devtools, since the cache works there. Obviously the second is a bit more complex. what do you think about it?

In which way it works for devtools? I don't understand.

How do browser extensions solve this? Is it possible to use the UA in the cache key?

**Comment by uazo** [comment]
> In which way it works for devtools? I don't understand.

follow this:
https://source.chromium.org/chromium/chromium/src/+/master:content/browser/devtools/protocol/emulation_handler.cc;l=399

**Comment by SumatraPeter** [comment]
@csagan5: On the Customize User Agent settings page, would it be possible to also display what the standard mobile and desktop mode UAs are, preferably in a manner so that we can copy them easily?

**Comment by csagan5** [comment]
@SumatraPeter you have to open a feature request, this PR is closed and merged

**Comment by SumatraPeter** [comment]
@csagan5: OK, done - https://github.com/bromite/bromite/issues/961 :)
